dist:
  module: go.opentelemetry.io/collector/cmd/otelcorecol
  name: asserts-otel-collector
  description: Local OpenTelemetry Collector binary, testing only.
  version: 0.81.0-dev
  otelcol_version: 0.81.0
  output_path: ./
  debug_compilation: false

receivers:
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.81.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/jaegerreceiver v0.81.0
exporters:
  - gomod: go.opentelemetry.io/collector/exporter/loggingexporter v0.81.0
  - gomod: go.opentelemetry.io/collector/exporter/otlpexporter v0.81.0
  - gomod: go.opentelemetry.io/collector/exporter/otlphttpexporter v0.81.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/awsxrayexporter v0.81.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/googlecloudexporter v0.81.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/jaegerexporter v0.81.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusexporter v0.81.0
extensions:
  - gomod: go.opentelemetry.io/collector/extension/ballastextension v0.81.0
  - gomod: go.opentelemetry.io/collector/extension/zpagesextension v0.81.0
processors:
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/groupbytraceprocessor v0.81.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/resourcedetectionprocessor v0.81.0
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.81.0
  - gomod: go.opentelemetry.io/collector/processor/memorylimiterprocessor v0.81.0
  - gomod: github.com/asserts/asserts-otel-processor/assertsprocessor v0.0.88
connectors:
  - gomod: go.opentelemetry.io/collector/connector/forwardconnector v0.81.0
