receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4315
      http:
        endpoint: 0.0.0.0:4316

exporters:
  otlp:
    endpoint: http://0.0.0.0:4317
    tls:
      insecure: true
  prometheus:
    namespace: default
    endpoint: 0.0.0.0:8889

processors:
  assertsprocessor:
    asserts_server:
      endpoint: https://chief.app.dev.asserts.ai/api-server
    asserts_env: dev
    asserts_site: dev
    capture_metrics: true
    custom_attributes:
      "asserts.error.type":
        "default":
          - replacement: client_errors
            regexp: 4..
            source_attributes: ["http.status_code"]
            span_kinds: ["Client", "Server"]
          - replacement: server_errors
            regexp: 5..
            source_attributes: ["http.status_code"]
            span_kinds: ["Client", "Server"]
      "asserts.request.context":
        robot-shop#payment:
          - source_attributes: ["http.url"]
            span_kinds: ["Server"]
            regexp: "http://cart:8080(/cart)/anonymous-.*"
            replacement: $1
          - source_attributes: ["http.url"]
            span_kinds: ["Server"]
            regex: "http://user:8080(/check)/anonymous-.*"
            replacement: $1
        robot-shop#shipping:
          - source_attributes: ["http.url"]
            span_kinds: ["Server"]
            regexp: "http://cart:8080(/shipping)/anonymous-.*"
            replacement: $1
        default:
          - source_attributes: ["http.route"]
            regexp: "(.+)"
            span_kinds: ["Server"]
            replacement: $1
          - source_attributes: ["http.url"]
            span_kinds: ["Server"]
            regexp: "https?://.+?((/[^/?]+){1,2}).*"
            replacement: $1
    attributes_as_metric_labels:
      - "rpc.system"
      - "rpc.service"
      - "rpc.method"
      - "aws.table.name"
      - "aws.queue.url"
service:
  telemetry:
    logs:
      level: "debug"
  pipelines:
    traces:
      receivers: [otlp]
      processors: [assertsprocessor]
      exporters: [otlp]
    metrics:
      receivers: [otlp]
      exporters: [prometheus]
    logs:
      receivers: [otlp]
      exporters: [otlp]
