dist:
  module: go.opentelemetry.io/collector/cmd/otelcorecol
  name: asserts-otel-collector
  description: Local OpenTelemetry Collector binary, testing only.
  version: 0.72.0-dev
  otelcol_version: 0.72.0
  output_path: ./
  debug_compilation: false

receivers:
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.72.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/jaegerreceiver v0.72.0
exporters:
  - gomod: go.opentelemetry.io/collector/exporter/loggingexporter v0.72.0
  - gomod: go.opentelemetry.io/collector/exporter/otlpexporter v0.72.0
  - gomod: go.opentelemetry.io/collector/exporter/otlphttpexporter v0.72.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusexporter v0.72.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/jaegerexporter v0.72.0
extensions:
  - gomod: go.opentelemetry.io/collector/extension/ballastextension v0.72.0
  - gomod: go.opentelemetry.io/collector/extension/zpagesextension v0.72.0
processors:
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.72.0
  - gomod: go.opentelemetry.io/collector/processor/memorylimiterprocessor v0.72.0
  - gomod: github.com/asserts/asserts-otel-processor/assertsprocessor v0.0.54
connectors:
  - gomod: go.opentelemetry.io/collector/connector/forwardconnector v0.72.0