receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4315
      http:
        endpoint: 0.0.0.0:4316

exporters:
  otlp:
    endpoint: http://0.0.0.0:4317
    tls:
      insecure: true
  prometheus:
    namespace: default
    endpoint: 0.0.0.0:8889

processors:
  assertsprocessor:
    asserts_server:
      endpoint: https://chief.app.dev.asserts.ai/api-server
    asserts_env: dev
    asserts_site: dev
    capture_metrics: true
    request_context_regex:
      - attr_name: "http.route"
        regex: "(.+)"
      - attr_name: "http.url"
        regex: "https?://.+?((/[^/?]+){1,2}).*"
    attributes_as_metric_labels:
      - "rpc.system"
      - "rpc.service"
      - "rpc.method"
      - "aws.table.name"
      - "aws.queue.url"
service:
  telemetry:
    logs:
      level: "debug"
  pipelines:
    traces:
      receivers: [otlp]
      processors: [assertsprocessor]
      exporters: [otlp]
    metrics:
      receivers: [otlp]
      exporters: [prometheus]
    logs:
      receivers: [otlp]
      exporters: [otlp]
