receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4315
      http:
        endpoint: 0.0.0.0:4316

exporters:
  otlp:
    endpoint: http://0.0.0.0:4317
    tls:
      insecure: true
  prometheus:
    namespace: default
    endpoint: 0.0.0.0:8889

processors:
  assertsprocessor:
    asserts_server:
      endpoint: https://chief.app.dev.asserts.ai/api-server
      username: HcbAlB7nUFhXpm3rJKvi
      password: Ri7q1J/Fq+/rwfQDeP/bbBfYpK0JydvMInEitdqr
    asserts_env: dev
    asserts_site: dev
    capture_metrics: true
    error_type_config:
      "http.status_code":
        - error_type: client_errors
          value_match_regex: 4..
        - error_type: server_errors
          value_match_regex: 5..
    request_context_regex:
      robot-shop#payment:
        - attr_name: "http.url"
          span_kind: "Server"
          regex: "http://cart:8080(/cart)/anonymous-.*"
        - attr_name: "http.url"
          span_kind: "Server"
          regex: "http://user:8080(/check)/anonymous-.*"
      robot-shop#shipping:
        - attr_name: "http.url"
          span_kind: "Server"
          regex: "http://cart:8080(/shipping)/anonymous-.*"
      default:
        - attr_name: "http.route"
          regex: "(.+)"
          span_kind: "Server"
        - attr_name: "http.url"
          span_kind: "Server"
          regex: "https?://.+?((/[^/?]+){1,2}).*"
    attributes_as_metric_labels:
      - "rpc.system"
      - "rpc.service"
      - "rpc.method"
      - "aws.table.name"
      - "aws.queue.url"
service:
  telemetry:
    logs:
      level: "debug"
  pipelines:
    traces:
      receivers: [otlp]
      processors: [assertsprocessor]
      exporters: [otlp]
    metrics:
      receivers: [otlp]
      exporters: [prometheus]
    logs:
      receivers: [otlp]
      exporters: [otlp]
