AWSTemplateFormatVersion: 2010-09-09
Description: Asserts OTEL Collector IAM Stack
Parameters:
  AssertsEnvironment:
    Type: String
    Description: The installation environment name
Resources:
  AssertsOTELECSExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "AssertsOTELECSExecutionRole-${AssertsEnvironment}"
      Tags:
        - Key: Vendor
          Value: Asserts
        - Key: "asserts:component"
          Value: "AWS Exporter"
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly"
        - "arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy"
      Policies:
        - PolicyName: !Sub "AssertsOTELECSExecutionSecretsReadPolicy-${AssertsEnvironment}"
          PolicyDocument: !Sub >
            {
              "Version": "2012-10-17",
              "Statement": [
                {
                  "Effect": "Allow",
                  "Action": [
                    "secretsmanager:GetSecretValue",
                    "kms:Decrypt",
                    "secretsmanager:DescribeSecret"
                  ],
                  "Resource": [
                    "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:AssertsApiServerCredentials-${AssertsEnvironment}*"
                  ]
                },
                {
                  "Sid": "VisualEditor1",
                  "Effect": "Allow",
                  "Action": "secretsmanager:ListSecrets",
                  "Resource": [
                    "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:AssertsApiServerCredentials-${AssertsEnvironment}*"
                  ]
                }
              ]
            }
        - PolicyName: !Sub "AssertsLogGroupReadWritePolicy-${AssertsEnvironment}"
          PolicyDocument: !Sub >
            {
              "Version": "2012-10-17",
              "Statement": [
                {
                  "Effect": "Allow",
                  "Action": [
                    "logs:CreateLogStream",
                    "logs:PutLogEvents"
                  ],
                  "Resource": "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:asserts-otel-collector-${AssertsEnvironment}:*"
                }
              ]
            }
  AssertsOTELECSTaskRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "AssertsOTELECSTaskRole-${AssertsEnvironment}"
      Tags:
        - Key: Vendor
          Value: Asserts
        - Key: "asserts:component"
          Value: "AWS Exporter"
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AWSXrayWriteOnlyAccess"
      Policies:
        - PolicyName: !Sub "AssertsOTELECSTaskSecretsReadPolicy-${AssertsEnvironment}"
          PolicyDocument: !Sub >
            {
              "Version": "2012-10-17",
              "Statement": [
                {
                  "Effect": "Allow",
                  "Action": [
                    "secretsmanager:GetSecretValue",
                    "kms:Decrypt",
                    "secretsmanager:DescribeSecret"
                  ],
                  "Resource": [
                    "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:AssertsApiServerCredentials-${AssertsEnvironment}*"
                  ]
                },
                {
                  "Effect": "Allow",
                  "Action": "secretsmanager:ListSecrets",
                  "Resource": [
                    "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:AssertsApiServerCredentials-${AssertsEnvironment}*"
                  ]
                }
              ]
            }
        - PolicyName: !Sub "AssertsOTELCollectorRolePolicy-${AssertsEnvironment}"
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Resource: "*"
                Action:
                  - autoscaling:DescribeAutoScalingGroups
                  - autoscaling:DescribeTags
                  - autoscaling:DescribeLoadBalancers
                  - dynamodb:ListTables
                  - ec2:DescribeVolumes
                  - ec2:DescribeInstances
                  - ec2:DescribeSubnets
                  - ecs:DescribeClusters
                  - ecs:DescribeServices
                  - ecs:DescribeTaskDefinition
                  - ecs:DescribeTasks
                  - ecs:ListAccountSettings
                  - ecs:ListClusters
                  - ecs:ListServices
                  - ecs:ListTaskDefinitionFamilies
                  - ecs:ListTaskDefinitions
                  - elasticloadbalancing:DescribeListeners
                  - elasticloadbalancing:DescribeLoadBalancers
                  - elasticloadbalancing:DescribeRules
                  - elasticloadbalancing:DescribeTags
                  - elasticloadbalancing:DescribeTargetGroups
                  - elasticloadbalancing:DescribeTargetHealth
                  - firehose:ListDeliveryStreams
                  - kinesis:ListStreamConsumers
                  - kinesis:ListStreams
                  - kinesis:ListTagsForStream
                  - kinesisanalytics:ListApplications
                  - lambda:GetAccountSettings
                  - lambda:ListEventSourceMappings
                  - lambda:ListFunctions
                  - redshift:DescribeClusters
                  - redshift:ListDatabases
                  - redshift:ListTables
                  - s3:ListAllMyBuckets
                  - sns:ListTopics
                  - sqs:ListQueues
                  - tag:GetResources
                  - elasticmapreduce:ListClusters
                  - cloudwatch:DescribeAlarms
                  - cloudwatch:GetMetricData
                  - cloudwatch:ListMetrics