AWSTemplateFormatVersion: 2010-09-09
Description: Asserts OTEL Collector ALB Stack
Parameters:
  AssertsEnvironment:
    Type: String
    Description: The installation environment name
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: "Id of VPC in which Asserts OTEL Collector is being installed"
  ALBSubnets:
    Type: List<AWS::EC2::Subnet::Id>
    Description: "The IDs of the subnets on which the OTEL Collector ALB should be installed."
  ALBSecurityGroupId:
    Type: String
Resources:
  OTELCollectorALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Join [ "-", [ "Asserts-OTEL-Collector", !Ref AssertsEnvironment ] ]
      Tags:
        - Key: Vendor
          Value: Asserts
        - Key: "asserts:component"
          Value: "Asserts OTEL Collector"
        - Key: Environment
          Value: !Ref AssertsEnvironment
      Scheme: internet-facing
      Subnets: !Ref ALBSubnets
      SecurityGroups:
        - !Ref ALBSecurityGroupId
      Type: application
      IpAddressType: "ipv4"
      LoadBalancerAttributes:
        - Key: "access_logs.s3.enabled"
          Value: "false"
        - Key: "idle_timeout.timeout_seconds"
          Value: "60"
        - Key: "deletion_protection.enabled"
          Value: "false"
        - Key: "routing.http2.enabled"
          Value: "true"
        - Key: "routing.http.drop_invalid_header_fields.enabled"
          Value: "false"

#  OTELCollectorGRPCTargetGroup:
#    Type: AWS::ElasticLoadBalancingV2::TargetGroup
#    Properties:
#      Port: 4317
#      Protocol: HTTP
#      ProtocolVersion: gRPC
#      Tags:
#        - Key: Vendor
#          Value: Asserts
#        - Key: "asserts:component"
#          Value: "Asserts OTEL Collector"
#        - Key: Environment
#          Value: !Ref AssertsEnvironment
#      TargetType: ip
#      VpcId: !Ref VpcId

  OTELCollectorHTTPTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Port: 4318
      Protocol: HTTP
      HealthCheckEnabled: true
      HealthCheckIntervalSeconds: 30
      HealthCheckPath: "/metrics"
      HealthCheckProtocol: "HTTP"
      HealthCheckPort: 9465
      HealthCheckTimeoutSeconds: 15
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 10
      Matcher:
        HttpCode: 200
      Tags:
        - Key: Vendor
          Value: Asserts
        - Key: "asserts:component"
          Value: "Asserts OTEL Collector"
        - Key: Environment
          Value: !Ref AssertsEnvironment
      TargetType: ip
      VpcId: !Ref VpcId

  OTELCollectorALBHTTPListener:
    Type: "AWS::ElasticLoadBalancingV2::Listener"
    Properties:
      LoadBalancerArn: !Ref OTELCollectorALB
      Port: 4318
      Protocol: HTTP
      DefaultActions:
        - Order: 1
          Type: "forward"
          ForwardConfig:
            TargetGroups:
              - TargetGroupArn: !Ref OTELCollectorHTTPTargetGroup
                Weight: 1
            TargetGroupStickinessConfig:
              Enabled: false

  OTELCollectorALBHTTPListenerRule:
    Type: "AWS::ElasticLoadBalancingV2::ListenerRule"
    Properties:
      Priority: "1"
      ListenerArn: !Ref OTELCollectorALBHTTPListener
      Conditions:
        - Field: path-pattern
          PathPatternConfig:
            Values:
              - "/v1/*"
      Actions:
        - Type: "forward"
          TargetGroupArn: !Ref OTELCollectorHTTPTargetGroup
          Order: 1
          ForwardConfig:
            TargetGroups:
              - TargetGroupArn: !Ref OTELCollectorHTTPTargetGroup
                Weight: 1
            TargetGroupStickinessConfig:
              Enabled: false

#  OTELCollectorALBGRPCListener:
#    Type: "AWS::ElasticLoadBalancingV2::Listener"
#    Properties:
#      LoadBalancerArn: !Ref OTELCollectorALB
#      Port: 4317
#      Protocol: HTTP
#      DefaultActions:
#        - Order: 1
#          Type: "forward"
#          ForwardConfig:
#            TargetGroups:
#              - TargetGroupArn: !Ref OTELCollectorGRPCTargetGroup
#                Weight: 1
#            TargetGroupStickinessConfig:
#              Enabled: false
#
#  OTELCollectorALBGRPCListenerRule:
#    Type: "AWS::ElasticLoadBalancingV2::ListenerRule"
#    Properties:
#      Priority: "1"
#      ListenerArn: !Ref OTELCollectorALBGRPCListener
#      Conditions:
#        - Field: path-pattern
#          PathPatternConfig:
#            Values:
#              - "*"
#      Actions:
#        - Type: "forward"
#          TargetGroupArn: !Ref OTELCollectorGRPCTargetGroup
#          Order: 1
#          ForwardConfig:
#            TargetGroups:
#              - TargetGroupArn: !Ref OTELCollectorGRPCTargetGroup
#                Weight: 1
#            TargetGroupStickinessConfig:
#              Enabled: false
Outputs:
  ALBDNSName:
    Description: "The DNS name for the load balancer."
    Value: !GetAtt OTELCollectorALB.DNSName
#  CollectorGRPCTargetGroupARN:
#    Value: !Ref OTELCollectorGRPCTargetGroup
  CollectorHTTPTargetGroupARN:
    Value: !Ref OTELCollectorHTTPTargetGroup